<?php

$dataSystemsDesc = 'This subject introduces the concepts of systems engineering for complex, data-centric systems. It explores the lifecycle of data-centric systems from initial design through to system development, then production and ongoing management. The subject is project based. Students do a combination of individual self-directed study and project work as a team.';

$introDataEngDesc = 'This subject introduces students to the foundations of data engineering and the data industry. Data is all pervasive in modern society. Data engineers both build the infrastructure that enables this, but also participate in the manipulation and analysis of the data.

The subject takes a practical, hands-on approach designed to inspire and motivate students in all facets of data engineering. These include the gathering, processing and analysis of data, as well as decision-making and actuation in relation to data. Students create their own data sets to use in a number of group and individual projects.

MATLAB is core to the subject and students become proficient in its use for modelling and analysis.

This is a field of practice subject undertaken by all students enrolled in a Data Engineering major. Students from other majors or faculties may also enrol.';

$itsescDesc = "This subject focuses on developing engineering students' approaches to understanding the interactions between engineering and society from a philosophical, sociological and political perspective. The subject introduces students to theoretical frameworks and research tools for researching these interactions. Topical case studies of new technologies and engineering projects are examined to ground the learning in students engineering contexts.";

$erpDesc = "The capstone project consists of subjects that aim to consolidate the application of engineering knowledge and skills for problem-solving. It is carried out in two phases: the preparation and planning phase in this subject, and the implementation phase in 41030 Engineering Capstone. Students undertake the capstone project in their final year of study.

In these two subjects students solve complicated engineering problems that respond to industrial, academic and personal interests, taking a systematic approach. The types of capstone projects that students can undertake include research and development, investigation, experimentation, design, building and manufacturing. Students in this subject develop skills in research design, project management and critical communication.

This subject, Engineering Research Preparation, emphasises the development of the theoretical framework and the associated project plan for a student's capstone project. The subject is followed by the implementation phase in 41030. Both subjects aim to strengthen students' knowledge application, and research and communication competencies to the graduate level for engineering practice as per Engineers Australia Stage 1 competencies and faculty graduate attributes. Both subjects also align with Australian Qualifications Framework criteria of graduation concerning knowledge, skills development and application to the bachelors (level 7) and honours (level 8) degrees.";

$engCapDesc = "This subject is the second phase of students' capstone project and involves the implementation and write-up of their final project. Students can refer to 41029 Engineering Research Preparation as a reminder of what needs to be completed prior to the commencement of this second phase of work.";

$dataEngDesignDesc = 'This subject focuses on the creation of ideas for new data engineering systems. One way in which data engineering differs from traditional engineering disciplines is the rapid pace at which new ideas emerge, often due to technology developments. This subject encourages students to devise and prototype future applications of data-intensive systems that benefit society. Students take an interdisciplinary approach and explore human-centred design methods for technology such as design thinking approaches.';

$cProgDesc = 'Data engineers use C programming language to collect, process and store data. This is an introductory subject to high-level procedural programming using C programming language. Students learn basic programming concepts such as conditional statements, iteration, functions, arrays, file processing, data structures and memory management using pointers. The subject also introduces how to compile C source code using the GNU toolchain, link binary object files and run executable files. As a data engineer would, students go through the complete development cycle, incorporating analysis of complex problems, programming solution design, implementation in C, debugging and testing.';

$infoSigDesc = 'This subject provides the theoretical foundations of information theory and signal processing that prepare students for both industry- and research-oriented careers. Later subjects in data engineering, communications systems and image processing rely heavily on the mathematical groundwork and system framework in this subject. A strong laboratory component is emphasised to equip students with hands-on experience and the ability to apply theoretical concepts to a number of practical communication and signal/image processing systems. Students are also encouraged to be involved in a collaborative research project in information and signal theory.';

$introDataAnalyDesc = 'Data analytics is the art and science of turning large quantities of usually incomprehensive data into meaningful and commercially valuable information. It is the basis of modern computer analytics and intelligence. It includes a number of IT areas, such as statistical methods for identifying patterns in data and making inferences; database technologies for managing the data sets to be mined; a range of intelligent technologies that derive automatically patterns from data; and visualisation and other multimedia techniques that support human pattern discovery capabilities. This subject offers the foundations of data analytics, data mining and knowledge discovery methods and their application to practical problems. It brings together the state-of-the-art research and practical techniques in data analytics, providing students with the necessary knowledge and capacity to initiate and conduct data mining research and development projects, and professionally communicate with analytics experts.';

$embSoftDesc = "This subject develops the student's technical knowledge of the design, implementation and testing of software modules and application frameworks for embedded systems.

Students develop their ability to interpret and evaluate a set of software specifications and work in small groups to write software modules and applications for an embedded system. Students are introduced to abstracting hardware functionality into software modules and researching and implementing software data structures.

Students develop their ability to test and modify their software to ensure compliance with the application specifications and be introduced to reviewing and evaluating their own and others software.

The technical content is contextualised in a project in which students analyse the requirements of an embedded system and design the software to meet those requirements. Skills in debugging software are also developed through the practice-based nature of the subject.";

$iotDesc = 'The Internet of Things (IoT) is a distributed system, in which autonomous devices, sometimes called motes, collect environmental data (such as location, speed, temperature, humidity and sound level) or, more recently, medical data (such as heart rate, blood oxygen level and pulse rate). The data is collected across the network, aggregated and fed into business applications. Sensor and actuator networks, telemetry, data processing, distributed data bases, machine vision, AI and analytics are enablers for various applications, including environmental monitoring and control, agricultural monitoring and control, medical monitoring, habitat monitoring and military surveillance. In this subject, students learn the theory, the concepts and the practice of the new paradigm. By designing and developing a medium-complexity, IoT-based application, students learn new skills, learn the benefits of the technology and explore new models of service deployment and data delivery.';

$realtimeOSDesc = 'This subject addresses the purposes, design alternatives and uses of computer operating systems for programming in embedded systems, PC, and servers. After several weeks studying the areas of responsibility that an operating system possesses in the context of a conventional computing environment (PC and server), a treatment of operating systems in support of meeting real-time computing requirements, such as managing operating for programming on PC and server, is completed.

Topics include: process management, scheduling and inter-process communication, memory management and I/O device management. Comparisons of designs including monolithic and microkernel approaches. Embedded systems are explored as case studies for investigating operating systems modifications. The Linux kernel is studied as an example of a UNIX environment and programming exercises are completed in POSIX compliant C. Real-time systems are studied including real-time kernels and real-time CPU scheduling.';

$netFunDesc = "Today's internet is arguably the largest engineered system ever created by humanity, carrying petabytes of data every minute. It is important for data engineers to understand how data is transferred through the internet, and the guiding principles and structures of data transportation designs.

This subject provides students with a modern introduction to the dynamic field of computer networking, including layered network architecture and the TCP/IP protocol suite. Student practical works include observing network traffic in action and building their own network applications through socket programming. Students also have hands-on opportunities to build their own networks using Cisco network equipment.

By developing problem-solving and design skills in this subject, students also acquire the ability to select the most appropriate network services, and design and develop network applications, e.g. web server and client, to achieve the best data performance.";

$sacDesc = "This subject introduces students to programming hardware devices to collect data, make control decisions and cause actions in the physical world. This subject develops students' theoretical and practical understanding of sensing and actuation, sensor and actuator selection, evaluation of control hardware and software, modelling, interfacing, signal measurement and data processing and image processing and visualisation. The subject incorporates online and virtual learning environments. Students bring their own devices to implement practical systems that they can use at home or work.";

$eefDesc = 'In this subject students develop the ability to cost, manage and value complex engineering projects through engagement with the commercial side of projects and businesses. In the UTS model of global practice-oriented learning, students learn and apply the economic and financial techniques of engineering economy, such as cash flow, valuation and costing, and develop confidence in the language of finance and general management in the engineering domain by analysing financial reports to propose new financial and operating strategies.';

$appStudioBDesc = 'This is the second subject of the applications studio. It allows students to continue exploring applications of data engineering through a combination of individual self-directed study and project work as a team. At this stage of the course, students should also be developing technical depth in parallel with the applications studio, and therefore the studio is an opportunity for students to further extend their technical knowledge in their chosen specialisation area. The theme of the applications studio is for students to develop and apply professional engineering skills while addressing a complex problem. Students work with mentors and facilitators throughout the session, and the individual tasks to be completed are guided by a learning contract established at the beginning of the studio.

Students work with students in 41086 Data Engineering Studio 2A, i.e. there is one applications studio class with both junior and senior students working together. Roles within the studio project teams reflect this, and students in this subject are expected to take on more responsibility within their teams.';

$engComDesc = "This subject develops students' professional engineering practice skills within the context of a real-life engineering project, through the Engineers Without Borders (EWB) Challenge. Students work in teams to create an appropriate design solution for a given problem as set out in the EWB Challenge Design Brief. While appreciating the central role of effective communication and teamwork in engineering practice, students develop an understanding of the social, cultural, economic and environmental responsibilities of a professional engineer. This subject is a starting point for students' ongoing professional development that they undertake throughout their studies and as a professional engineer in their career.

The skills introduced include understanding and applying principles and theories of human communication; researching the various discipline areas that inform the development of an engineering design solution; applying the engineering design process to identify, formulate and design a solution to solve a problem; written and oral communication for engineering contexts; expressing engineering concepts through visual communication; conversing mathematically; and, leading and participating in team processes. This subject provides multiple formative assessment opportunities for students to receive feedback and develop their work before submitting a summative team assessment.";

$mm1Desc = 'This subject develops the knowledge and skills necessary for problem-solving and mathematical modelling at an introductory level. Differential calculus is applied to model situations in science and engineering that involve oscillations. Integral calculus is used to solve selected problems involving first- and second-order differential equations, and to calculate areas, volumes, lengths and other physical quantities. Vectors, matrix multiplication and determinants are introduced and applied to problem-solving and modelling. Sequences and series are reviewed and power series introduced where power series are used to approximate more functions.';